name: CI

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: pruebas-unitarias
        run: mvn test
      - name: empaquetar
        run: mvn package -DskipTests=true

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pruebas-funcionales
        run: |
          cp -r target/Baloncesto /usr/local/tomcat/webapps
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3307"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
          mvn failsafe:integration-test failsafe:verify

  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: calidad-codigo
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000  -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=sonar

  deploy:
    runs-on: ubuntu-latest
    needs: qa
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
      - name: Desplegar en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: baloncesto-lauracercas
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.war