name: CI

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: pruebas-unitarias
        run: mvn test
      - name: empaquetar
        run: mvn package -DskipTests=true

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pruebas-funcionales
        run:
          cp -r target/Baloncesto /usr/local/tomcat/webapps
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
          mvn failsafe:integration-test failsafe:verify
  
  qa:
    needs: test
    runs-on: self-hosted
    steps:
      - name: calidad-codigo
        run: echo "calidad-codigo"

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"